spring:
  profiles:
    active: dev   # 指定默认激活 dev 配置

  application:
    name: hongjing

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.whu.hongjing.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
